### ISSUE TITLE
Michigan legislator start/end dates have been corrupted

### ISSUE THREAD

**Issue by calebclimatecabinet** [openstates/issues#1300]
The start and end dates for Michigan legislators are inconsistent.

**Issue Description:**
Many Michigan legislators (I haven't checked other states) have start and end dates that are incorrect. This seems to be the result of recent updates.

For example, Ranjeev Puri has this data:
```yaml
roles:
- start_date: 2023-01-01
  type: lower
  jurisdiction: ocd-jurisdiction/country:us/state:mi/government
  district: '24'
- start_date: 2021-01-01
  end_date: 2022-12-31
  type: lower
  jurisdiction: ocd-jurisdiction/country:us/state:mi/government
  district: '24'
- end_date: 2023-01-01
  type: lower
  jurisdiction: ocd-jurisdiction/country:us/state:mi/government
  district: '21'
```
This shows that he wrapped up his term in HD-24 and HD21 at the exact same time (well, one day apart). The correct data would show him in district 21 from 2021-2022 and district 24 from 2023 to now.

I'm seeing similar conflicts in about half of the Michigan legislators (house and senate).

**URL where this issue may be seen (API or OpenStates.org):**
[Ranjeev Puri](https://github.com/openstates/people/blob/df443b7f0e909b9b5f7f30ed4f19b6c61f9e20f6/data/mi/legislature/Ranjeev-Puri-1a16bef8-b655-46da-a5c5-07a8c5569eed.yml#L4)
