### ISSUE TITLE
MA: Update people data

### ISSUE THREAD

**Issue by bhrutledge** [openstates/issues#211]
Following up on https://github.com/openstates/issues/issues/207. Blocked by https://github.com/openstates/people/pull/374.

Based on my read of the [contributing guide](https://docs.openstates.org/en/latest/contributing/people.html) and some experimentation, I think the process will be something like:

- Update MA `people` scraper output
    - Probably just `Capitol office -> Capitol Office`
- Run MA `people` scraper
- Run `to_yaml.py`
    - This should handle the `email` schema change described in <https://github.com/openstates/issues/issues/207#issuecomment-752134795>
- Run `merge.py --incoming`
    - Fix removal of `start_date`
    - Add special case for `contact_details` to avoid appending duplicate entries
    - `git rm` unmodified YAML files with outdated rep names (e.g. [`Bradford-R-Hill`](https://github.com/openstates/people/blob/main/data/ma/legislature/Bradford-R-Hill-6e64e8db-c1f5-4f72-994b-dbe9cfdab8a5.yml) will be `Bradford-Hill`)
- Handle new and retired people
    - There's `vacancies` in [openstates/metadata/_creation/settings.yml](https://github.com/openstates/openstates-core/blob/c5e33f2e9d5e06c8ddf94bd51fdea98bb85d4548/openstates/metadata/_creation/settings.yml#L316-L331) and [people/settings.yml](https://github.com/openstates/people/blob/471905141ed1aab580303cc3bedd7abe3f819692/settings.yml#L22-L35), and they're slightly different. Does one take precedence?

Depending on the timing, maybe it's worth doing this in two batches: updating the current data (since some vacancies have been filled), and then updating for the new legislative session, once https://malegislature.gov/Legislators/ has been updated.

Outdated `vacancies`, with comments for current legislators:

```yaml
- chamber: upper
  district: Plymouth and Barnstable
  vacant_until: 2020-05-01
  # https://malegislature.gov/Legislators/Profile/SLM0
- chamber: upper
  district: Second Hampden and Hampshire
  vacant_until: 2020-05-01
  # https://malegislature.gov/Legislators/Profile/JCV0
- chamber: lower
  district: Third Bristol
  vacant_until: 2020-05-01
  # https://malegislature.gov/Legislators/Profile/CAD1
- chamber: lower
  district: Thirty-Second Middlesex
  vacant_until: 2020-05-01
  # https://malegislature.gov/Legislators/Profile/KLG1
- chamber: lower
  district: Thirty-Seventh Middlesex
  vacant_until: 2020-05-01
  # https://malegislature.gov/Legislators/Profile/DAS1
```
